# Generated by Django 2.1.2 on 2018-10-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('CONTENT', models.TextField()),
                ('CREATE_TIME', models.DateTimeField(auto_now=True)),
                ('CREATOR', models.CharField(max_length=10)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ISFEEDBACK', models.BooleanField()),
                ('SENDDEPARTMENT', models.CharField(max_length=100)),
                ('TASKSTATUS', models.CharField(max_length=2)),
                ('TITLE', models.CharField(max_length=256)),
                ('TYPE', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Task',
                'ordering': ('ID',),
            },
        ),
    ]
