# Generated by Django 2.1.2 on 2018-11-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ISFEEDBACK',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
