# Generated by Django 2.1.2 on 2018-11-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0003_auto_20181101_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FILE_URL', models.FilePathField()),
            ],
        ),
    ]
