# Generated by Django 2.1.2 on 2018-11-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0004_filebox'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDir',
            fields=[
                ('FILEID', models.AutoField(primary_key=True, serialize=False)),
                ('FILEDIR', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskFileDir',
            fields=[
                ('DIRID', models.AutoField(primary_key=True, serialize=False)),
                ('TASKID', models.OneToOneField(on_delete='', to='oa.Task')),
            ],
        ),
        migrations.DeleteModel(
            name='FileBox',
        ),
        migrations.AddField(
            model_name='filedir',
            name='TASKFILEDIR',
            field=models.ForeignKey(on_delete='', to='oa.TaskFileDir'),
        ),
    ]
