# Generated by Django 2.1.2 on 2018-11-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0005_auto_20181102_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfiledir',
            name='TASKID',
        ),
        migrations.AddField(
            model_name='task',
            name='TASKFILEDIRID',
            field=models.OneToOneField(default=1, on_delete='', to='oa.TaskFileDir'),
            preserve_default=False,
        ),
    ]
