# Generated by Django 2.1.2 on 2018-11-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0006_auto_20181102_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TASKFILEDIRID',
            new_name='TASKFILEDIR',
        ),
    ]
