# Generated by Django 2.1.2 on 2018-11-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0007_auto_20181102_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TASKFILEDIR',
            field=models.OneToOneField(on_delete='', related_name='TASKFILEDIR', to='oa.TaskFileDir'),
        ),
    ]
