# Generated by Django 2.1.2 on 2018-11-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0008_auto_20181102_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfiledir',
            name='CREATETIME',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
